version: "3"
services:
  db:
    image: postgres:9.6.9
    volumes:
      - ./tmp/db:/var/lib/postgresql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sqlhunt
    ports:
      - "3000:3000"
    depends_on:
      - db
